const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  SCHEDULED: 'SCHEDULED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  UPDATED: 'UPDATED',
  FAILED: 'FAILED'
});

const PAYOUT_STATUS = Object.freeze({
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  DENIED: 'DENIED',
  REJECTED: 'REJECTED'
});

const RISK_DECISION = Object.freeze({
  APPROVED: 'APPROVED',
  REVIEW: 'REVIEW',
  BLOCKED: 'BLOCKED'
});

const LEDGER_ENTRY_TYPE = Object.freeze({
  INVOICE_PENDING_CREDIT: 'INVOICE_PENDING_CREDIT',
  FUNDS_RELEASE: 'FUNDS_RELEASE',
  PAYOUT_RESERVE: 'PAYOUT_RESERVE',
  PAYOUT_SETTLED: 'PAYOUT_SETTLED',
  PAYOUT_RELEASE_REFUND: 'PAYOUT_RELEASE_REFUND',
  INVOICE_REFUND_ADJUSTMENT: 'INVOICE_REFUND_ADJUSTMENT',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT'
});

const BALANCE_BUCKET = Object.freeze({
  PENDING: 'PENDING',
  AVAILABLE: 'AVAILABLE',
  FROZEN: 'FROZEN',
  PAID_OUT: 'PAID_OUT'
});

const AUDIT_ACTOR_TYPE = Object.freeze({
  SYSTEM: 'SYSTEM',
  USER: 'USER',
  ADMIN: 'ADMIN',
  WEBHOOK: 'WEBHOOK'
});

const WEBHOOK_PROCESSING_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  IGNORED: 'IGNORED'
});

const RISK_FLAG_SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

const RISK_FLAG_STATUS = Object.freeze({
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED'
});

const RECIPIENT_TYPE = Object.freeze({
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  PAYPAL_ID: 'PAYPAL_ID'
});

const RECEIPT_TYPE = Object.freeze({
  BANK: 'bank',
  EMAIL: 'email'
});

const RECEIPT_STATUS = Object.freeze({
  GENERATED: 'GENERATED',
  EMAILED: 'EMAILED'
});

const POINT_TRANSACTION_TYPE = Object.freeze({
  SIGNUP_BONUS: 'SIGNUP_BONUS',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  RECEIPT_SPEND: 'RECEIPT_SPEND',
  EMAIL_SPEND: 'EMAIL_SPEND',
  TOP_UP_PURCHASE: 'TOP_UP_PURCHASE',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT'
});

const TOP_UP_ORDER_STATUS = Object.freeze({
  PENDING: 'pending',
  AWAITING_CONFIRMATION: 'awaiting_confirmation',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
});

const EMAIL_DISPATCH_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  LOCAL_ONLY: 'LOCAL_ONLY'
});

module.exports = {
  INVOICE_STATUS,
  PAYOUT_STATUS,
  RISK_DECISION,
  LEDGER_ENTRY_TYPE,
  BALANCE_BUCKET,
  AUDIT_ACTOR_TYPE,
  WEBHOOK_PROCESSING_STATUS,
  RISK_FLAG_SEVERITY,
  RISK_FLAG_STATUS,
  RECIPIENT_TYPE,
  RECEIPT_TYPE,
  RECEIPT_STATUS,
  POINT_TRANSACTION_TYPE,
  TOP_UP_ORDER_STATUS,
  EMAIL_DISPATCH_STATUS
};
